spring.application.name=FashionVista_Backend

# Server Configuration

server.port=${PORT:8085}


# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Upload File Configuration (Cho upload ?nh s?n ph?m)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.signerKey=${JWT_SECRET_KEY}
jwt.valid-duration=90000
jwt.refreshable-duration=14

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Email Configuration
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${SENDER_EMAIL}
brevo.api.url=${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}





# Application Configuration
app.name=Sixthsoul
app.frontend.url=${FRONTEND_URL}

# VNPay Configuration
vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.pay-url=${VNPAY_PAY_URL}
vnpay.return-url=${VNPAY_RETURN_URL}
vnpay.ipn-url=${VNPAY_IPN_URL}

# Login Activity Configuration
login-activity.enabled=true
login-activity.retention-days=90
