server {
    listen 80;
    server_name ops.sixthsoul.com;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ops.sixthsoul.com;

    ssl_certificate /etc/letsencrypt/live/ops.sixthsoul.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ops.sixthsoul.com/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Nginx serving the Admin Dashboard build files
    location / {
        root /usr/share/nginx/html/admin;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
